services:
  parking_postgress_container:
    image: postgres
    container_name: parkingPostgresSQLContainer
    ports:
      - "5432:5432"
    env_file:
      - ./postgres.env
    volumes:
      - parking_postgres_data_container:/var/lib/postgresql/data

volumes:
  parking_postgres_data_container:
    driver: local
